/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.util.List;
import javax.swing.table.DefaultTableModel;
import model.ModelProduto;
import model.ModelProdutoE;
import DAO.DaoProdutos;
import conexoes.FabricaConexao;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.JOptionPane;

/**
 *
 * @author Administrador
 */
public class viewProdutos extends javax.swing.JFrame {
    
    ModelProdutoE produto = new ModelProdutoE();
    ModelProduto produto2 = new ModelProduto();
    DaoProdutos dao = new DaoProdutos();
    
    boolean novoatualizar = true;
    int id=0;
    /**
     * Creates new form viewProdutos
     */
    // função para habilirat ou sedabilisat os campos;
    public void habilitar(Boolean condicao) {
        jTextFieldProduto.setEnabled(condicao);
        jTextFieldPreco.setEnabled(condicao);
    }
    
    public viewProdutos() {
      
        initComponents();
        habilitar(true);
      
    }
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jToggleButtonRemover = new javax.swing.JToggleButton();
        jToggleButtonMostrar = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldProduto = new javax.swing.JTextField();
        jTextFieldPreco = new javax.swing.JTextField();
        jTextFieldConsultaId = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableProduto = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jToggleButtonNovo = new javax.swing.JToggleButton();
        jToggleButtonLimparTabela = new javax.swing.JToggleButton();
        jToggleButtonMostrarr = new javax.swing.JToggleButton();
        jToggleButtonConsultar = new javax.swing.JToggleButton();
        jToggleButtonDeletarById = new javax.swing.JToggleButton();
        jToggleButtonAtualizar = new javax.swing.JToggleButton();

        jToggleButtonRemover.setText("Remover");
        jToggleButtonRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonRemoverActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Produtos");

        jLabel1.setText("PRODUTO");

        jLabel2.setText("PREÇO POR UNIDADE");

        jLabel3.setText("COD. PRODUTO");

        jTextFieldProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldProdutoActionPerformed(evt);
            }
        });

        jTextFieldPreco.setToolTipText("");

        jTextFieldConsultaId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldConsultaIdActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 13, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 115, Short.MAX_VALUE)
        );

        jTableProduto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CODIGO", "NOME PROD", "PREÇO POR UNI"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableProduto);

        jLabel4.setText("REGISTAR PRODUTOS");

        jToggleButtonNovo.setText("Novo");
        jToggleButtonNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonNovoActionPerformed(evt);
            }
        });

        jToggleButtonLimparTabela.setText("Limpar Tabela");
        jToggleButtonLimparTabela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonLimparTabelaActionPerformed(evt);
            }
        });

        jToggleButtonMostrarr.setText("Mostrar dados do BD");
        jToggleButtonMostrarr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonMostrarrActionPerformed(evt);
            }
        });

        jToggleButtonConsultar.setText("Consultar");
        jToggleButtonConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonConsultarActionPerformed(evt);
            }
        });

        jToggleButtonDeletarById.setText("Deletar");
        jToggleButtonDeletarById.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonDeletarByIdActionPerformed(evt);
            }
        });

        jToggleButtonAtualizar.setText("Atualizar");
        jToggleButtonAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonAtualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jToggleButtonMostrarLayout = new javax.swing.GroupLayout(jToggleButtonMostrar);
        jToggleButtonMostrar.setLayout(jToggleButtonMostrarLayout);
        jToggleButtonMostrarLayout.setHorizontalGroup(
            jToggleButtonMostrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jToggleButtonMostrarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jToggleButtonMostrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jToggleButtonMostrarLayout.createSequentialGroup()
                        .addGroup(jToggleButtonMostrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jToggleButtonMostrarLayout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jToggleButtonMostrarLayout.createSequentialGroup()
                                .addGroup(jToggleButtonMostrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jToggleButtonMostrarLayout.createSequentialGroup()
                                        .addComponent(jTextFieldProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(28, 28, 28))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jToggleButtonMostrarLayout.createSequentialGroup()
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)))
                                .addGroup(jToggleButtonMostrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jToggleButtonMostrarLayout.createSequentialGroup()
                                        .addComponent(jTextFieldPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(jToggleButtonMostrarLayout.createSequentialGroup()
                                        .addComponent(jTextFieldConsultaId, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jToggleButtonConsultar))))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jToggleButtonMostrarLayout.createSequentialGroup()
                                .addGroup(jToggleButtonMostrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jToggleButtonMostrarLayout.createSequentialGroup()
                                        .addComponent(jToggleButtonNovo)
                                        .addGap(100, 100, 100)
                                        .addComponent(jToggleButtonAtualizar))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jToggleButtonMostrarLayout.createSequentialGroup()
                                        .addComponent(jToggleButtonDeletarById)
                                        .addGap(104, 104, 104)
                                        .addComponent(jToggleButtonLimparTabela)
                                        .addGap(50, 50, 50)
                                        .addComponent(jToggleButtonMostrarr)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jToggleButtonMostrarLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jToggleButtonMostrarLayout.setVerticalGroup(
            jToggleButtonMostrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jToggleButtonMostrarLayout.createSequentialGroup()
                .addGroup(jToggleButtonMostrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jToggleButtonMostrarLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(87, 87, 87)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jToggleButtonMostrarLayout.createSequentialGroup()
                        .addGroup(jToggleButtonMostrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jToggleButtonMostrarLayout.createSequentialGroup()
                                .addGap(76, 76, 76)
                                .addGroup(jToggleButtonMostrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jToggleButtonMostrarLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jToggleButtonMostrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextFieldConsultaId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jToggleButtonConsultar)
                                    .addComponent(jLabel3))
                                .addGap(39, 39, 39)))
                        .addGroup(jToggleButtonMostrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jToggleButtonMostrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jToggleButtonNovo)
                            .addComponent(jToggleButtonAtualizar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jToggleButtonMostrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jToggleButtonMostrarr)
                            .addComponent(jToggleButtonDeletarById)
                            .addComponent(jToggleButtonLimparTabela))))
                .addContainerGap(57, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToggleButtonMostrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToggleButtonMostrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButtonNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonNovoActionPerformed
        // Escrever os dados na tabela visual da interface 
           habilitar(true);
//        DefaultTableModel tbProduto = (DefaultTableModel) jTableProduto.getModel();
//        Object[] dados = {jTextFieldProduto.getText(), jTextFieldPreco.getText()};
//        tbProduto.addRow(dados);
//        Ecrever dados no Bando de Dados
        if (novoatualizar == true) {
            novo();
        } else if (novoatualizar == false) {
            alterar();

        }
        mostrarlista();

    }//GEN-LAST:event_jToggleButtonNovoActionPerformed

    private void jToggleButtonMostrarrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonMostrarrActionPerformed
        // Preencher a tabela com dado o BD da tabela produtos; falta imprimir a outras linhas.
         //classe onde esta as funçoes do BD(inserir, listar, remover etc
         // Declarar o obj de implemte uma funçao da classe DAOProduto
        mostrarlista();
    }//GEN-LAST:event_jToggleButtonMostrarrActionPerformed

    private void jTextFieldProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldProdutoActionPerformed

    private void jToggleButtonDeletarByIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonDeletarByIdActionPerformed
        // TODO add your handling code here:
        int id = this.jTableProduto.getSelectedRow();
        int a = (int) this.jTableProduto.getValueAt(id, 0);
        if(dao.remover(a)){
            JOptionPane.showMessageDialog(this, "Produto Expluido com Sucesso");
        }else JOptionPane.showMessageDialog(this, "Produto Não Expluido");
        mostrarlista();
         
    }//GEN-LAST:event_jToggleButtonDeletarByIdActionPerformed

    private void jToggleButtonLimparTabelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonLimparTabelaActionPerformed
        // TODO add your handling code here:
        DefaultTableModel tbProduto = (DefaultTableModel) jTableProduto.getModel(); // declarar modelo da tbl view
        tbProduto.setRowCount(0);
    }//GEN-LAST:event_jToggleButtonLimparTabelaActionPerformed

    private void jToggleButtonRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonRemoverActionPerformed
        // TODO add your handling cod
    }//GEN-LAST:event_jToggleButtonRemoverActionPerformed

    private void jToggleButtonAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonAtualizarActionPerformed
        // TODO add your handling code here:
        habilitar(true);
        int p = this.jTableProduto.getSelectedRow();
        id = (int) this.jTableProduto.getValueAt(p, 0);
        produto2 = dao.getProdutoById(id);
        this.jTextFieldProduto.setText(produto2.getProNome());
        this.jTextFieldPreco.setText(String.valueOf(produto2.getProPreco()));
        novoatualizar = false; 
    }//GEN-LAST:event_jToggleButtonAtualizarActionPerformed

    private void jToggleButtonConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonConsultarActionPerformed
        // COSULTAR PRODUTO POR ID
        produto2 = dao.getProdutoById(Integer.parseInt(this.jTextFieldConsultaId.getText()));
        DefaultTableModel tbProduto = (DefaultTableModel) jTableProduto.getModel(); // declarar modelo da tbl view
        tbProduto.setRowCount(0); //Limpar a tabela do jTable na interface
        Object[] dados = {produto2.getIdProduto(), produto2.getProNome(),
            produto2.getProPreco()};
        tbProduto.addRow(dados);
        

    }//GEN-LAST:event_jToggleButtonConsultarActionPerformed

    private void jTextFieldConsultaIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldConsultaIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldConsultaIdActionPerformed
    public void novo() {
        produto.setProNome(this.jTextFieldProduto.getText());
        produto.setProPreco(Double.parseDouble(this.jTextFieldPreco.getText()));
        dao.inserir(produto);

    }

    public void alterar() {
        produto.setProNome(this.jTextFieldProduto.getText());
        produto.setProPreco(Double.parseDouble(this.jTextFieldPreco.getText()));
        produto.setProId(id);
       if ( dao.atualizar(produto)){
        habilitar(false);
       }
    }
     public void mostrarlista(){
         List<ModelProduto> produtoss = dao.getProdutos();
         DefaultTableModel tbProduto = (DefaultTableModel) jTableProduto.getModel(); // declarar modelo da tbl view
        tbProduto.setRowCount(0); //Limpar a tabela do jTable na interface
        for (int i = 0; i < produtoss.size(); i++) {
            Object[] dados = {produtoss.get(i).getIdProduto(), produtoss.get(i).getProNome(),
                produtoss.get(i).getProPreco()
            };
            tbProduto.addRow(dados);
        }
     }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(viewProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(viewProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(viewProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(viewProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new viewProdutos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTableProduto;
    private javax.swing.JTextField jTextFieldConsultaId;
    private javax.swing.JTextField jTextFieldPreco;
    private javax.swing.JTextField jTextFieldProduto;
    private javax.swing.JToggleButton jToggleButtonAtualizar;
    private javax.swing.JToggleButton jToggleButtonConsultar;
    private javax.swing.JToggleButton jToggleButtonDeletarById;
    private javax.swing.JToggleButton jToggleButtonLimparTabela;
    private javax.swing.JPanel jToggleButtonMostrar;
    private javax.swing.JToggleButton jToggleButtonMostrarr;
    private javax.swing.JToggleButton jToggleButtonNovo;
    private javax.swing.JToggleButton jToggleButtonRemover;
    // End of variables declaration//GEN-END:variables
}
